colors: false

logging:

  # path to a file where cli logs will be saved.
  filename: /tmp/cloudify-makala/cloudify-cli.log

  # configuring level per logger
  loggers:

    # main logger of the cli. provides basic descriptions for executed operations.
    cloudify.cli.main: info

    # rest client http logs, including headers.
    cloudify.rest_client.http: info

import_resolver:
  parameters:
    rules:
    - {'http://www.getcloudify.org/spec/cloudify/3.4.1/types.yaml': 'file:/opt/cfy/types/types.yaml'}
    - {'http://www.getcloudify.org/spec/aws-plugin/1.4.1': 'file:/opt/cfy/plugins/aws-plugin'}
    - {'http://www.getcloudify.org/spec/openstack-plugin/1.4': 'file:/opt/cfy/plugins/openstack-plugin'}
    - {'http://www.getcloudify.org/spec/fabric-plugin/1.4.1': 'file:/opt/cfy/plugins/fabric-plugin'}
    - {'http://www.getcloudify.org/spec/script-plugin/1.4': 'file:/opt/cfy/plugins/script-plugin'}
    - {'http://www.getcloudify.org/spec/diamond-plugin/1.3.3': 'file:/opt/cfy/plugins/diamond-plugin'}
    - {'http://www.getcloudify.org/spec/vsphere-plugin/2.0': 'file:/opt/cfy/plugins/vsphere-plugin'}
